CREATE TABLE CLIENT(
CLIENTID INTEGER NOT NULL AUTO_INCREMENT,
FIRSTNAME CHAR(25) NOT NULL,
LASTNAME CHAR(25) NOT NULL,
ADDRESS CHAR(100) NOT NULL,
CITY CHAR(75) NOT NULL,
STATE CHAR(2) NULL,
ZIP CHAR(5) NOT NULL,
PHONE CHAR(12) NOT NULL,
CELLPHONE CHAR(12) NULL,
REFERRAL INTEGER NULL,
EMAIL CHAR(100) NOT NULL,
CONSTRAINT CLIENT_PK PRIMARY KEY (CLIENTID)
);

CREATE TABLE PACKAGES(
PACKAGEID INTEGER NOT NULL AUTO_INCREMENT,
PRICE CHAR(18) NOT NULL,
DEPOSIT CHAR(18) NOT NULL,
TOTAL CHAR(18) NOT NULL,
P4X6 CHAR(5) NOT NULL,
P5X7 CHAR(5) NOT NULL,
P8X11 CHAR(5) NOT NULL,
CANVAS CHAR(5) NOT NULL,
DIGITALCOPY CHAR(1) NOT NULL,
ONLINEALBUM CHAR(1) NOT NULL,
WALLETS CHAR(5) NULL,
CONSTRAINT PACKAGES_PK PRIMARY KEY(PACKAGEID)
);


CREATE TABLE CAMERAS(
CAMERAID INTEGER NOT NULL AUTO_INCREMENT,
SHOTCOUNT INTEGER NOT NULL,
CAMERATYPE CHAR(18) NULL,
BATTERIES INTEGER NULL,
PRIMARYLENSE CHAR(18) NOT NULL,
CONSTRAINT CAMERAS_PK PRIMARY KEY(CAMERAID)
);

CREATE TABLE VENUES(
VENUEID INTEGER NOT NULL AUTO_INCREMENT,
VENUENAME CHAR(25) NOT NULL,
VENUEADDRESS CHAR(18) NOT NULL,
VENUECITY CHAR(18) NULL,
VENUESTATE CHAR(18) NULL,
VENUEZIP CHAR(10) NOT NULL,
VENUENUMBER CHAR(12) NOT NULL,
VENUECONTACTNAME CHAR(25) NULL,
VENUETYPE CHAR(18) NOT NULL,
CONSTRAINT VENUES_PK PRIMARY KEY(VENUEID)
);

CREATE TABLE EMPLOYEES(
EMPLOYEEID INTEGER NOT NULL AUTO_INCREMENT,
EMPFIRSTNAME CHAR(25) NOT NULL,
EMPLASTNAME CHAR(25) NOT NULL,
EMPADDRESS CHAR(100) NOT NULL,
EMPCITY CHAR(75) NULL,
EMPSTATE CHAR(2) NULL,
EMPZIP CHAR(10) NOT NULL,
EMPPHONE CHAR(12) NULL,
EMPCELLPHONE CHAR(12) NOT NULL,
EMPEMAIL CHAR(100) NOT NULL,
EMPPASS CHAR(16) NOT NULL,
CONSTRAINT EMPLOYEES_PK PRIMARY KEY(EMPLOYEEID)
);

CREATE TABLE PAYMENTS(
TRANSACTIONID INTEGER NOT NULL AUTO_INCREMENT,
ORDERID INTEGER NULL,
PAYMENTTYPE CHAR(18)  NULL,
PAYMANTDATE CHAR(12)  NULL,
PAYMENTAMMOUNT CHAR(10) NULL,
CONSTRAINT PAYMENTS_PK PRIMARY KEY(TRANSACTIONID)
);

CREATE TABLE PAYMENTHISTORY(
TRANSACTIONID INTEGER NOT NULL,
ORDERID INTEGER NOT NULL,
PAYMENTAMOUNT CHAR(18) NULL,
PAYMENTDATE CHAR(12) NULL,
DEPOSITDATE CHAR(12) NULL
);

CREATE TABLE ORDERS(
ORDERID     INTEGER NOT NULL AUTO_INCREMENT,
CLIENTID    INTEGER NOT NULL,
EMPLOYEEID  INTEGER NOT NULL,
PACKAGEID   INTEGER NOT NULL,
VENUEID     INTEGER NOT NULL,
CAMERAID    INTEGER NOT NULL,
EVENTTYPE   CHAR(18) NULL,
EVENTDATE   DATE NULL,
ACCESSORIES CHAR(255) NULL,
SPECIALREQUESTS CHAR(180) NULL,
CONSTRAINT  ORDERS_PK PRIMARY KEY(ORDERID)
);

ALTER TABLE PAYMENTHISTORY ADD CONSTRAINT PAYMENTHISTORY_ORDERS_FK FOREIGN KEY (ORDERID)
REFERENCES ORDERS (ORDERID);
ALTER TABLE PAYMENTHISTORY ADD CONSTRAINT PAYMENTHISTORY_PAYMENTS_FK FOREIGN KEY (TRANSACTIONID)
REFERENCES PAYMENTS (TRANSACTIONID);
ALTER TABLE PAYMENTS ADD CONSTRAINT PAYMENTS_ORDER_FK FOREIGN KEY (ORDERID)
REFERENCES ORDERS (ORDERID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_CLIENT_FK FOREIGN KEY (CLIENTID)
REFERENCES CLIENT (CLIENTID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_EMP_FK FOREIGN KEY (EMPLOYEEID)
REFERENCES EMPLOYEES (EMPLOYEEID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_PAK_FK FOREIGN KEY (PACKAGEID)
REFERENCES PACKAGES (PACKAGEID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_VEN_FK FOREIGN KEY (VENUEID)
REFERENCES VENUES (VENUEID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_CAM_FK FOREIGN KEY (CAMERAID)
REFERENCES CAMERAS (CAMERAID);
