INSERT INTO employees (EMPLOYEEID, EMPFIRTNAME, EMPLASTNAME, EMPADDRESS, EMPCITY, EMPSTATE, EMPZIP, EMPPHONE, EMPCELLPHONE, EMPEMAIL, EMPPASS)
VALUES ('1', 'David', 'Rivera', '1000 University Center Lane', 'Lawrenceville', 'GA', '30043', NULL, '123-555-1289', 'dav@email.com', 'password');

INSERT INTO employees (EMPLOYEEID, EMPFIRTNAME, EMPLASTNAME, EMPADDRESS, EMPCITY, EMPSTATE, EMPZIP, EMPPHONE, EMPCELLPHONE, EMPEMAIL, EMPPASS)
VALUES ('2', 'Sam', 'Allen', 'Highway 120', NULL, 'CA', '95321', NULL, '123-555-1289', 'sam@email.com', 'password');
